In [1]:
#importing libraries dataset
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('weight-height.csv')

In [3]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
df.replace(to_replace=["Male", "Female"], value=[1,0], inplace=True) #male=1 ' female=0'

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   int64  
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 200.6 KB


In [6]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [7]:
df.Gender.value_counts()

1    5000
0    3555
Name: Gender, dtype: int64

# Step 01 - Regression

In [8]:
#Seperate X,y
x = df.drop('Weight', axis=1)
y = df[['Weight']]

In [9]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y,test_size=30, random_state= 10)

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
lr = LinearRegression()

In [14]:
lr.fit(xtrain, ytrain)

LinearRegression()

In [15]:
lr.predict([[1,74.110105]])

C:\Users\Rahman\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[217.34660397]])

In [16]:
df['Predicted Weight'] = lr.predict(x)
df.head()

Gender     Height      Weight  Predicted Weight
0       1  73.847017  241.893563        215.774714
1       1  68.781904  162.310473        185.511834
2       1  74.110105  212.740856        217.346606
3       1  71.730978  220.042470        203.131872
4       1  69.881796  206.349801        192.083434

In [17]:
from sklearn.metrics import mean_squared_error

In [18]:
mse = mean_squared_error(ytest, lr.predict(xtest))

In [19]:
mse

97.24190223194738

In [20]:
lr.score(xtest, ytest)

0.9026389925802443

# KNeighborsRegressor 

In [21]:
from sklearn.neighbors import KNeighborsRegressor

In [22]:
kn = KNeighborsRegressor(n_neighbors=100)

In [23]:
kn.fit(xtrain, ytrain)

KNeighborsRegressor(n_neighbors=100)

In [24]:
df['KNN Predicted Weight'] = kn.predict(x)
df.head()

Gender     Height      Weight  Predicted Weight  KNN Predicted Weight
0       1  73.847017  241.893563        215.774714            216.526195
1       1  68.781904  162.310473        185.511834            184.989547
2       1  74.110105  212.740856        217.346606            217.132309
3       1  71.730978  220.042470        203.131872            202.550471
4       1  69.881796  206.349801        192.083434            192.750645

In [25]:
mse = mean_squared_error(ytest, kn.predict(xtest))

In [26]:
mse

94.30976694943833

In [27]:
kn.score(xtest, ytest)

0.9055747192417318

# Step 02 - Classification

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
x = df.drop('Gender', axis=1)
y = df[['Gender']]

In [30]:
y.head()

Gender
0       1
1       1
2       1
3       1
4       1

In [31]:
x.head()

Height      Weight  Predicted Weight  KNN Predicted Weight
0  73.847017  241.893563        215.774714            216.526195
1  68.781904  162.310473        185.511834            184.989547
2  74.110105  212.740856        217.346606            217.132309
3  71.730978  220.042470        203.131872            202.550471
4  69.881796  206.349801        192.083434            192.750645

In [32]:
knc = KNeighborsClassifier(n_neighbors= 70)

In [33]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y,test_size=30, random_state= 3)

In [34]:
knc.fit(xtrain, ytrain)

C:\Users\Rahman\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=70)

In [35]:
knc.predict(xtest)

C:\Users\Rahman\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1], dtype=int64)

In [36]:
from sklearn.metrics import accuracy_score

In [38]:
y_pred = knc.predict(xtest)
print(y_pred)

[0 0 1 1 0 1 1 1 1 0 1 0 0 1 0 0 0 0 1 1 0 0 1 0 0 0 1 0 0 1]


C:\Users\Rahman\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [40]:
accuracy = accuracy_score(ytest, y_pred )

In [41]:
accuracy

0.9333333333333333